## YAML Template.
---
version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version          
  build:
    commands:
      - echo Build started on `date`
      - echo Build started on `date`
      - echo Building the Docker image... 
      - mvn package      
  post_build:
    commands:
      - echo Build completed on `date`         
artifacts:
    files:     
      - target/cidelivery-1.0-SNAPSHOT.jar
